# -*- coding: utf-8 -*-
"""Die Herleitung jeder Formel des Kurses, deutsch und englisch.

Drei Regeln fuer jeden Eintrag:

1. **Jedes Formelzeichen wird definiert**, mit Bedeutung und Einheit,
   bevor es auftaucht.
2. **Jede Formel wird hergeleitet** -- auch die, die erst in einer
   Herleitung auftaucht. Eine Begruendung, die ihrerseits eine
   unbegruendete Formel benutzt, hat nichts erklaert, sondern nur
   verschoben. Deshalb steht die Auftriebsgleichung hier ausgerechnet
   und nicht als gegeben.
3. **Jede sagt, wo sie aufhoert zu gelten.** Eine Faustformel, die man
   nur auswendig kann, hilft genau so lange, wie die Lage zum Lehrbuch
   passt.
"""
from __future__ import unicode_literals


def t(de, en):
    return {"de": de, "en": en}


# Die Auftriebsgleichung steht unter mehreren Herleitungen. Deshalb einmal
# ordentlich, und dann ueberall dieselbe.
AUFTRIEB = t(
    "## Vorab: woher die Auftriebsgleichung kommt\n\n"
    "**Formelzeichen:** `ρ` Luftdichte, kg/m³. `v` Anstroemgeschwindigkeit, "
    "m/s. `A` Flaeche, m². `q` Staudruck, Pa. `L` Auftrieb, N. "
    "`S` Fluegelflaeche, m². `c_A` Auftriebsbeiwert, dimensionslos.\n\n"
    "Zuerst der **Staudruck**. Luft, die auf eine Flaeche trifft und dort "
    "zur Ruhe kommt, gibt ihre Bewegungsenergie ab. Je Sekunde trifft die "
    "Masse `ρ·A·v` auf die Flaeche `A`, und jedes Kilogramm davon bringt "
    "`½v²` an Energie mit. Leistung ist Energie je Zeit, Kraft ist "
    "Leistung durch Geschwindigkeit:\n\n"
    "    Leistung = (ρ·A·v) · ½v²\n"
    "    Kraft    = Leistung / v = ½·ρ·v²·A\n\n"
    "Der Druck ist Kraft durch Flaeche, also\n\n"
    "    q = ½·ρ·v²\n\n"
    "Das ist der Staudruck, und er steckt in jeder aerodynamischen Kraft. "
    "Die Probe auf die Einheiten: kg/m³ · m²/s² = kg/(m·s²) = N/m² = Pa.\n\n"
    "Der **Auftrieb** ist dann dieser Druck, mal der Fluegelflaeche, mal "
    "einer Zahl, die beschreibt, wie gut dieser Fluegel bei diesem "
    "Anstellwinkel den Druck in Auftrieb umsetzt:\n\n"
    "    L = q · S · c_A = ½·ρ·v²·S·c_A\n\n"
    "`c_A` ist keine Naturkonstante, sondern eine gemessene Eigenschaft "
    "von Profil und Anstellwinkel. Entscheidend fuer alles Folgende ist "
    "nur: **Bei festem Anstellwinkel ist L proportional zu v².**",

    "## First: where the lift equation comes from\n\n"
    "**Symbols:** `ρ` air density, kg/m³. `v` airspeed, m/s. `A` area, "
    "m². `q` dynamic pressure, Pa. `L` lift, N. `S` wing area, m². "
    "`C_L` lift coefficient, dimensionless.\n\n"
    "First the **dynamic pressure**. Air that meets a surface and is "
    "brought to rest gives up its kinetic energy. Each second the mass "
    "`ρ·A·v` arrives at the area `A`, and every kilogram of it brings "
    "`½v²` of energy. Power is energy per time, force is power divided by "
    "speed:\n\n"
    "    power = (ρ·A·v) · ½v²\n"
    "    force = power / v = ½·ρ·v²·A\n\n"
    "Pressure is force over area, hence\n\n"
    "    q = ½·ρ·v²\n\n"
    "That is the dynamic pressure, and it sits inside every aerodynamic "
    "force. The check on units: kg/m³ · m²/s² = kg/(m·s²) = N/m² = Pa.\n\n"
    "**Lift** is then that pressure, times the wing area, times a number "
    "describing how well this wing at this angle of attack turns the "
    "pressure into lift:\n\n"
    "    L = q · S · C_L = ½·ρ·v²·S·C_L\n\n"
    "`C_L` is not a constant of nature but a measured property of "
    "aerofoil and angle of attack. All that matters for what follows: "
    "**at a fixed angle of attack, L is proportional to v².**")


HERLEITUNGEN = {

"w-basis": t(
    "## Formelzeichen\n\n"
    "`T` Lufttemperatur, °C. `T_d` Taupunkt, °C. Die **Spreizung** ist "
    "`T − T_d`, in Grad. `Γ_d` trockenadiabatischer Temperaturgradient, "
    "°C je 100 m. `g` Fallbeschleunigung, 9,81 m/s². `c_p` spezifische "
    "Waermekapazitaet der Luft bei festem Druck, 1005 J/(kg·K).\n\n"
    "## Vorab: woher die 1 °C je 100 m kommen\n\n"
    "Ein aufsteigendes Luftpaket tauscht mit seiner Umgebung so gut wie "
    "keine Waerme aus — Luft leitet schlecht, und es geht schnell. Es "
    "dehnt sich aber aus, weil der Aussendruck faellt, und diese "
    "Ausdehnung kostet Arbeit. Die Arbeit kommt aus der inneren Energie, "
    "also kuehlt es ab.\n\n"
    "In Zahlen: Der erste Hauptsatz ohne Waermezufuhr sagt "
    "`c_p·dT = (1/ρ)·dp`, und die hydrostatische Grundgleichung sagt "
    "`dp = −ρ·g·dh` (hergeleitet in der Lektion zum Hoehenmesser). "
    "Zusammengesetzt kuerzt sich ρ weg:\n\n"
    "    c_p·dT = −g·dh      →      dT/dh = −g/c_p\n\n"
    "Eingesetzt:\n\n"
    "    Γ_d = 9,81 / 1005 = 0,00976 K/m ≈ 0,98 °C je 100 m\n\n"
    "Daher die Eins. Sie ist keine Erfahrung, sondern steht in zwei "
    "Naturkonstanten.\n\n"
    "## Und warum der Taupunkt nur um 0,2 °C je 100 m faellt\n\n"
    "Das Wasser bleibt im Paket; es wird nur auf ein groesseres Volumen "
    "verteilt. Der Partialdruck des Wasserdampfs sinkt deshalb im selben "
    "Verhaeltnis wie der Gesamtdruck. Der Taupunkt ist die Temperatur, "
    "bei der dieser Partialdruck gerade Saettigungsdruck waere — und weil "
    "der Saettigungsdruck sehr steil mit der Temperatur waechst "
    "(Clausius-Clapeyron), aendert ein maessiger Druckabfall den Taupunkt "
    "nur wenig. Gemessen sind es rund **0,2 °C je 100 m**.\n\n"
    "## Herleitung: woher die 125 kommen\n\n"
    "Zwei Temperaturen laufen beim Aufsteigen aufeinander zu: die "
    "Lufttemperatur mit 1,0, der Taupunkt mit 0,2 °C je 100 m. Die "
    "Spreizung schliesst sich also mit der Differenz:\n\n"
    "    1,0 − 0,2 = 0,8 °C je 100 m\n\n"
    "Kondensiert wird, wenn die Spreizung aufgebraucht ist. Also:\n\n"
    "    Hoehe = Spreizung ÷ 0,8 °C/100 m = Spreizung × 125 m/°C\n\n"
    "**Wo die Formel bricht.** Sie unterstellt, dass das Paket vom Boden "
    "bis zur Basis trocken aufsteigt und unterwegs keine Luft mit anderer "
    "Feuchte einmischt. Nach Regen, ueber Wasser oder in einer "
    "Luftmassengrenze stimmt beides nicht, und die Basis liegt tiefer als "
    "gerechnet.",

    "## Symbols\n\n"
    "`T` air temperature, °C. `T_d` dew point, °C. The **spread** is "
    "`T − T_d`, in degrees. `Γ_d` dry adiabatic lapse rate, °C per 100 m. "
    "`g` gravitational acceleration, 9.81 m/s². `c_p` specific heat of "
    "air at constant pressure, 1005 J/(kg·K).\n\n"
    "## First: where the 1 °C per 100 m comes from\n\n"
    "A rising parcel exchanges almost no heat with its surroundings — air "
    "conducts badly and the ascent is quick. But it expands, because the "
    "outside pressure falls, and that expansion costs work. The work "
    "comes out of the internal energy, so the parcel cools.\n\n"
    "In numbers: the first law without heat input says "
    "`c_p·dT = (1/ρ)·dp`, and the hydrostatic equation says "
    "`dp = −ρ·g·dh` (derived in the altimeter lesson). Put together, ρ "
    "cancels:\n\n"
    "    c_p·dT = −g·dh      →      dT/dh = −g/c_p\n\n"
    "Filling in:\n\n"
    "    Γ_d = 9.81 / 1005 = 0.00976 K/m ≈ 0.98 °C per 100 m\n\n"
    "Hence the one. It is not experience but two constants of nature.\n\n"
    "## And why the dew point only falls 0.2 °C per 100 m\n\n"
    "The water stays in the parcel; it is merely spread over a larger "
    "volume. The partial pressure of the vapour therefore drops in the "
    "same ratio as the total pressure. The dew point is the temperature "
    "at which that partial pressure would just be saturation pressure — "
    "and because saturation pressure rises very steeply with temperature "
    "(Clausius-Clapeyron), a moderate pressure drop moves the dew point "
    "only a little. Measured: about **0.2 °C per 100 m**.\n\n"
    "## Derivation: where the 125 comes from\n\n"
    "Two temperatures close on each other as the air rises: the air "
    "temperature at 1.0, the dew point at 0.2 °C per 100 m. So the spread "
    "closes at the difference:\n\n"
    "    1.0 − 0.2 = 0.8 °C per 100 m\n\n"
    "Condensation happens when the spread is used up. Hence:\n\n"
    "    height = spread ÷ 0.8 °C/100 m = spread × 125 m/°C\n\n"
    "**Where it breaks.** It assumes the parcel rises dry from the ground "
    "to the base and mixes in no air of different humidity on the way. "
    "After rain, over water, or at an air mass boundary neither holds, "
    "and the base sits lower than the sum says."),

"a-polare": t(
    "## Formelzeichen\n\n"
    "`L` Auftrieb, N. `D` Widerstand, N. `G` Gewicht, N. `E` Gleitzahl, "
    "dimensionslos. `γ` Gleitwinkel gegen die Waagrechte. `v` "
    "Fluggeschwindigkeit, m/s. `w` Sinkgeschwindigkeit, m/s.\n\n"
    "## Herleitung: warum Strecke = Hoehe × Gleitzahl\n\n"
    "Im stationaeren Gleitflug aendert sich nichts mehr: Die Summe aller "
    "Kraefte ist null. Auftrieb steht senkrecht zur Flugbahn, Widerstand "
    "entgegen der Flugbahn, das Gewicht senkrecht nach unten. Zerlegt man "
    "das Gewicht entlang und quer zur Bahn, ergeben sich zwei "
    "Gleichungen:\n\n"
    "    entlang der Bahn:  G·sin γ = D\n"
    "    quer zur Bahn:     G·cos γ = L\n\n"
    "Die erste durch die zweite geteilt — `G` kuerzt sich weg:\n\n"
    "    tan γ = D / L\n\n"
    "Der Tangens eines Winkels ist Gegenkathete durch Ankathete, hier "
    "also **Hoehenverlust durch Strecke**. Damit ist\n\n"
    "    Strecke / Hoehe = L / D = Gleitzahl E\n\n"
    "Die Gleitzahl ist also nichts anderes als das Verhaeltnis von "
    "Auftrieb zu Widerstand. E = 38 heisst: 38 Meter Strecke je Meter "
    "Hoehe. Aus 900 m werden 34,2 km.\n\n"
    "**Bemerkenswert:** Das Gewicht faellt heraus. Ein voll mit Wasser "
    "beladener Segler gleitet genauso weit wie ein leerer — nur "
    "schneller, und schneller wieder unten. Genau deshalb nimmt man "
    "Ballast bei starker Thermik und laesst ihn bei schwacher.\n\n"
    "## Und warum die Tangente vom Ursprung\n\n"
    "Die Polare traegt Sinken `w` ueber Fahrt `v` auf. Fuer jeden Punkt "
    "darauf ist\n\n"
    "    E = v / w\n\n"
    "denn in einer Sekunde kommt man `v` weit und faellt `w` tief. Das "
    "ist die Steigung des Strahls vom Ursprung zu diesem Punkt. Am "
    "weitesten kommt man, wo dieser Strahl am flachsten ist — und "
    "flacher als die Beruehrende geht nicht, ohne die Polare zu "
    "verlassen. Deshalb die Tangente.\n\n"
    "Bei Gegenwind `v_w` gilt ueber Grund `E = (v − v_w)/w`. Das ist "
    "derselbe Ausdruck, nur mit dem Ursprung um `v_w` nach links "
    "verschoben: gleiche Konstruktion, neuer Beruehrpunkt, hoehere Fahrt.",

    "## Symbols\n\n"
    "`L` lift, N. `D` drag, N. `W` weight, N. `E` glide ratio, "
    "dimensionless. `γ` glide angle from the horizontal. `v` airspeed, "
    "m/s. `w` sink rate, m/s.\n\n"
    "## Derivation: why distance = height × glide ratio\n\n"
    "In a steady glide nothing changes any more: the sum of all forces is "
    "zero. Lift is perpendicular to the flight path, drag along it, "
    "weight straight down. Resolving the weight along and across the "
    "path gives two equations:\n\n"
    "    along the path:   W·sin γ = D\n"
    "    across the path:  W·cos γ = L\n\n"
    "Divide the first by the second — `W` cancels:\n\n"
    "    tan γ = D / L\n\n"
    "The tangent of an angle is opposite over adjacent, here **height "
    "lost over distance flown**. So\n\n"
    "    distance / height = L / D = glide ratio E\n\n"
    "The glide ratio is nothing but the lift-to-drag ratio. E = 38 means "
    "38 metres of distance per metre of height. 900 m becomes 34.2 km.\n\n"
    "**Worth noting:** the weight drops out. A glider full of water "
    "glides exactly as far as an empty one — only faster, and back on the "
    "ground sooner. That is precisely why you carry ballast in strong "
    "conditions and leave it in weak ones.\n\n"
    "## And why the tangent from the origin\n\n"
    "The polar plots sink `w` against speed `v`. For any point on it\n\n"
    "    E = v / w\n\n"
    "because in one second you travel `v` and drop `w`. That is the slope "
    "of the ray from the origin to that point. You get furthest where "
    "that ray is flattest — and no ray is flatter than the tangent "
    "without leaving the curve. Hence the tangent.\n\n"
    "In a headwind `v_w` the ground figure is `E = (v − v_w)/w`. Same "
    "expression, with the origin shifted left by `v_w`: same "
    "construction, new touching point, higher speed."),

"a-ueberziehen": t(
    "## Formelzeichen\n\n"
    "`L` Auftrieb, N. `G` Gewicht, N. `n` Lastvielfaches `L/G`, "
    "dimensionslos. `φ` Schraeglage (Querneigung). `v_s` "
    "Ueberziehgeschwindigkeit im Geradeausflug, m/s. Weitere Zeichen im "
    "Abschnitt zur Auftriebsgleichung.\n\n"
    + AUFTRIEB["de"] + "\n\n"
    "## Herleitung: woher n = 1/cos φ kommt\n\n"
    "Im sauberen Kurvenflug hat der Auftrieb zwei Aufgaben zugleich. "
    "Kippt man ihn um die Schraeglage φ, zerfaellt er in zwei Anteile:\n\n"
    "* senkrecht: **L · cos φ** — der traegt das Gewicht,\n"
    "* waagrecht: **L · sin φ** — der zieht in die Kurve.\n\n"
    "Damit die Hoehe gehalten wird, muss der senkrechte Anteil genau das "
    "Gewicht tragen:\n\n"
    "    L · cos φ = G      →      L = G / cos φ\n\n"
    "Das Lastvielfache ist definiert als `n = L/G`, also\n\n"
    "    n = 1 / cos φ\n\n"
    "45°: cos 45° = 0,707, also n = 1,41. 60°: cos 60° = 0,5, also n = 2. "
    "Bei 90° waere cos φ = 0 und n unendlich — ein Messerflug traegt kein "
    "Gewicht, und genau deshalb geht er nicht stationaer.\n\n"
    "## Und die Wurzel bei der Ueberziehgeschwindigkeit\n\n"
    "Aus der Auftriebsgleichung oben: `L = ½·ρ·v²·S·c_A`. Ueberzogen wird "
    "immer beim **selben** groessten `c_A` — das ist eine Eigenschaft des "
    "Fluegels, nicht der Lage. Beim Ueberziehen ist also alles fest ausser "
    "`v` und `L`, damit ist `L ∝ v²`.\n\n"
    "Im Geradeausflug muss L = G sein, in der Kurve L = n·G. Verhaeltnis "
    "bilden, alles Feste kuerzt sich weg:\n\n"
    "    v_kurve² / v_s² = (n·G) / G = n\n"
    "    v_kurve = v_s · √n\n\n"
    "Daher die Zahlen: √1,15 = 1,07 (+7 %), √1,41 = 1,19 (+19 %), "
    "√2,00 = 1,41 (+41 %).\n\n"
    "**Das Gefaehrliche daran** ist der Unterschied der beiden Reihen. Die "
    "Last waechst schneller als die Geschwindigkeit: Bei 60° traegt man "
    "das doppelte Gewicht, muss aber nur 41 % schneller fliegen. Wer nach "
    "Gefuehl fliegt, unterschaetzt darum immer die Last.\n\n"
    "**Wo es nicht gilt:** Die Rechnung setzt einen stationaeren, "
    "koordinierten Kurvenflug voraus. Im Schiebeflug, beim Abfangen oder "
    "in einer Boe ist `n` groesser, ohne dass die Schraeglage es "
    "verraet.",

    "## Symbols\n\n"
    "`L` lift, N. `W` weight, N. `n` load factor `L/W`, dimensionless. "
    "`φ` bank angle. `v_s` stall speed in level flight, m/s. Further "
    "symbols in the section on the lift equation.\n\n"
    + AUFTRIEB["en"] + "\n\n"
    "## Derivation: where n = 1/cos φ comes from\n\n"
    "In a clean turn the lift does two jobs at once. Tilted by the bank "
    "angle φ it splits into two parts:\n\n"
    "* vertical: **L · cos φ** — this carries the weight,\n"
    "* horizontal: **L · sin φ** — this pulls you round.\n\n"
    "To hold height the vertical part must carry exactly the weight:\n\n"
    "    L · cos φ = W      →      L = W / cos φ\n\n"
    "The load factor is defined as `n = L/W`, so\n\n"
    "    n = 1 / cos φ\n\n"
    "45°: cos 45° = 0.707, so n = 1.41. 60°: cos 60° = 0.5, so n = 2. At "
    "90° cos φ would be 0 and n infinite — knife edge carries no weight, "
    "which is exactly why it cannot be held.\n\n"
    "## And the square root in the stall speed\n\n"
    "From the lift equation above: `L = ½·ρ·v²·S·C_L`. A wing always "
    "stalls at the **same** maximum `C_L` — a property of the wing, not "
    "of the attitude. At the stall everything is fixed but `v` and `L`, "
    "so `L ∝ v²`.\n\n"
    "Level flight needs L = W, the turn needs L = n·W. Take the ratio; "
    "everything fixed cancels:\n\n"
    "    v_turn² / v_s² = (n·W) / W = n\n"
    "    v_turn = v_s · √n\n\n"
    "Hence the numbers: √1.15 = 1.07 (+7 %), √1.41 = 1.19 (+19 %), "
    "√2.00 = 1.41 (+41 %).\n\n"
    "**What makes it dangerous** is the gap between the two series. Load "
    "grows faster than speed: at 60° you carry twice the weight but need "
    "only 41 % more speed. Flying by feel therefore always underestimates "
    "the load.\n\n"
    "**Where it does not hold:** the calculation assumes a steady, "
    "coordinated turn. In a slip, in a pull-up or in a gust, `n` is "
    "larger without the bank angle showing it."),

"l-schwerpunkt": t(
    "## Formelzeichen\n\n"
    "`m_i` Einzelmasse, kg. `x_i` ihr Hebelarm von der Bezugsebene, mm — "
    "mit Vorzeichen. `x_s` Lage des Schwerpunkts, mm. `M` Moment, kg·mm. "
    "`F` Kraft, N. `Σ` Summenzeichen: addiere ueber alle i.\n\n"
    "## Vorab: was ein Moment ist\n\n"
    "Ein Moment ist Kraft mal Hebelarm:\n\n"
    "    M = F · x\n\n"
    "Es misst die Drehwirkung um einen Punkt. Deshalb kippt 10 kg weit "
    "vorn mehr als 50 kg nahe am Drehpunkt — die Masse allein sagt "
    "nichts. Weil bei allen Beitraegen dieselbe Fallbeschleunigung "
    "steckt, kuerzt sie sich in der ganzen Rechnung weg; man darf statt "
    "mit Kraeften gleich mit Massen rechnen.\n\n"
    "## Herleitung: warum man Momente addiert und nicht Massen\n\n"
    "Der Schwerpunkt ist definiert als der eine Punkt, an dem die "
    "Gesamtmasse dasselbe Moment erzeugt wie alle Einzelmassen zusammen. "
    "Das ist die ganze Definition, und als Gleichung um die "
    "Bezugsebene:\n\n"
    "    (Σ m_i) · x_s = Σ (m_i · x_i)\n\n"
    "Nach `x_s` aufgeloest:\n\n"
    "    x_s = Σ (m_i · x_i) / Σ m_i = Gesamtmoment / Gesamtmasse\n\n"
    "Im Beispiel: (75 000 + 70 × 100) / (250 + 70) = 82 000 / 320 = "
    "256,25 mm.\n\n"
    "**Worauf zu achten ist:** Alle Hebelarme muessen von **derselben** "
    "Bezugsebene aus gemessen sein, und zwar mit Vorzeichen. Etwas hinter "
    "der Bezugsebene hat einen negativen Hebelarm; wer das Vorzeichen "
    "vergisst, rechnet sich den Schwerpunkt in den gruenen Bereich, in "
    "dem er nicht liegt.",

    "## Symbols\n\n"
    "`m_i` individual mass, kg. `x_i` its arm from the datum, mm — with "
    "sign. `x_cg` position of the centre of gravity, mm. `M` moment, "
    "kg·mm. `F` force, N. `Σ` summation sign: add over all i.\n\n"
    "## First: what a moment is\n\n"
    "A moment is force times lever arm:\n\n"
    "    M = F · x\n\n"
    "It measures the turning effect about a point. That is why 10 kg well "
    "forward tips more than 50 kg near the pivot — mass alone says "
    "nothing. Because the same gravitational acceleration sits in every "
    "contribution, it cancels throughout; one may work with masses "
    "directly instead of forces.\n\n"
    "## Derivation: why you add moments, not masses\n\n"
    "The centre of gravity is defined as the one point at which the total "
    "mass produces the same moment as all the individual masses together. "
    "That is the whole definition, and as an equation about the datum:\n\n"
    "    (Σ m_i) · x_cg = Σ (m_i · x_i)\n\n"
    "Solved for `x_cg`:\n\n"
    "    x_cg = Σ (m_i · x_i) / Σ m_i = total moment / total mass\n\n"
    "In the example: (75 000 + 70 × 100) / (250 + 70) = 82 000 / 320 = "
    "256.25 mm.\n\n"
    "**What to watch:** every arm must be measured from the **same** "
    "datum, and with its sign. Anything behind the datum has a negative "
    "arm; forget the sign and you compute yourself into a green band you "
    "are not in."),

"l-startstrecke": t(
    "## Formelzeichen\n\n"
    "`ρ` Luftdichte, kg/m³. `p` Luftdruck, Pa. `T` absolute Temperatur, "
    "K. `R` spezifische Gaskonstante trockener Luft, 287 J/(kg·K). "
    "Weitere Zeichen im Abschnitt zur Auftriebsgleichung.\n\n"
    + AUFTRIEB["de"] + "\n\n"
    "## Vorab: woher ρ = p/(R·T) kommt\n\n"
    "Die allgemeine Gasgleichung lautet `p·V = m·R·T` — Druck mal Volumen "
    "ist Masse mal Gaskonstante mal absoluter Temperatur. Teilt man "
    "beide Seiten durch `V` und erkennt `m/V` als die Dichte:\n\n"
    "    p = ρ·R·T      →      ρ = p / (R·T)\n\n"
    "Beachte: **absolute** Temperatur in Kelvin. Mit °C gerechnet kommt "
    "Unsinn heraus, denn 0 °C ist kein Nullpunkt der Bewegung.\n\n"
    "## Herleitung: warum duenne Luft die Startstrecke verlaengert\n\n"
    "Abheben heisst: Der Auftrieb traegt das Gewicht.\n\n"
    "    ½ · ρ · v² · S · c_A = G\n\n"
    "Gewicht, Flaeche und der groesste brauchbare `c_A` aendern sich "
    "nicht, wenn es heiss wird. `ρ` schon. Nach `v` aufgeloest:\n\n"
    "    v = √( 2G / (ρ · S · c_A) )      also      v ∝ 1/√ρ\n\n"
    "Bei 10 % weniger Dichte braucht man also 1/√0,9 = 1,054, gut 5 % "
    "mehr **Fahrt ueber Grund** zum Abheben. Und weil die Rollstrecke "
    "etwa mit dem Quadrat der Abhebegeschwindigkeit waechst und der Motor "
    "in duenner Luft zugleich weniger leistet, ist der Zuschlag auf die "
    "Strecke deutlich groesser als die 5 % auf die Fahrt.\n\n"
    "**Woher die Dichte faellt.** Aus `ρ = p/(R·T)`: Hoher Platz heisst "
    "kleines `p`, heisser Tag grosses `T` — beides verkleinert ρ. Feuchte "
    "Luft ist uebrigens **leichter** als trockene, weil ein "
    "Wassermolekuel (18 u) weniger wiegt als das Stickstoff- (28 u) oder "
    "Sauerstoffmolekuel (32 u), das es verdraengt.\n\n"
    "Die **Dichtehoehe** fasst all das in eine Zahl: die Hoehe, in der "
    "die Normatmosphaere genau diese Dichte haette.",

    "## Symbols\n\n"
    "`ρ` air density, kg/m³. `p` air pressure, Pa. `T` absolute "
    "temperature, K. `R` specific gas constant of dry air, 287 J/(kg·K). "
    "Further symbols in the section on the lift equation.\n\n"
    + AUFTRIEB["en"] + "\n\n"
    "## First: where ρ = p/(R·T) comes from\n\n"
    "The gas law reads `p·V = m·R·T` — pressure times volume is mass "
    "times gas constant times absolute temperature. Divide both sides by "
    "`V` and recognise `m/V` as the density:\n\n"
    "    p = ρ·R·T      →      ρ = p / (R·T)\n\n"
    "Note: **absolute** temperature, in kelvin. Using °C gives nonsense, "
    "because 0 °C is not a zero point of motion.\n\n"
    "## Derivation: why thin air lengthens the take-off run\n\n"
    "Lifting off means lift carries the weight.\n\n"
    "    ½ · ρ · v² · S · C_L = W\n\n"
    "Weight, wing area and the largest usable `C_L` do not change when it "
    "gets hot. `ρ` does. Solved for `v`:\n\n"
    "    v = √( 2W / (ρ · S · C_L) )      so      v ∝ 1/√ρ\n\n"
    "With 10 % less density you need 1/√0.9 = 1.054, a good 5 % more "
    "**groundspeed** to unstick. And because the ground roll grows "
    "roughly with the square of the lift-off speed while the engine also "
    "delivers less in thin air, the penalty on distance is far larger "
    "than the 5 % on speed.\n\n"
    "**Where the density goes.** From `ρ = p/(R·T)`: a high field means "
    "small `p`, a hot day means large `T` — both shrink ρ. Humid air, "
    "incidentally, is **lighter** than dry air, because a water molecule "
    "(18 u) weighs less than the nitrogen (28 u) or oxygen molecule "
    "(32 u) it displaces.\n\n"
    "**Density altitude** packs all of this into one number: the altitude "
    "at which the standard atmosphere would have exactly this density."),

"r-hoehenmesser": t(
    "## Formelzeichen\n\n"
    "`p` Luftdruck, Pa (1 hPa = 100 Pa). `ρ` Luftdichte, kg/m³; in "
    "Meereshoehe 1,225. `g` Fallbeschleunigung, 9,81 m/s². `h` Hoehe, m. "
    "`dp`, `dh` kleine Aenderungen von Druck und Hoehe.\n\n"
    "## Herleitung: die hydrostatische Grundgleichung\n\n"
    "Der Luftdruck an einer Stelle ist das Gewicht der Luftsaeule "
    "darueber, verteilt auf die Flaeche. Steigt man um `dh`, faellt genau "
    "die Schicht `dh` aus dieser Saeule heraus.\n\n"
    "Diese Schicht hat ueber der Flaeche `A` das Volumen `A·dh`, also die "
    "Masse `ρ·A·dh` und das Gewicht `ρ·A·dh·g`. Ihr Beitrag zum Druck ist "
    "Gewicht durch Flaeche — `A` kuerzt sich weg:\n\n"
    "    dp = − ρ · g · dh\n\n"
    "Das Minus, weil der Druck nach oben abnimmt. Das ist die "
    "hydrostatische Grundgleichung, und sie gilt in jeder ruhenden "
    "Fluessigkeit und jedem ruhenden Gas.\n\n"
    "## Und warum ein Hektopascal rund acht Meter ist\n\n"
    "Nach `dh` aufgeloest und in Meereshoehe eingesetzt:\n\n"
    "    dh = dp / (ρ·g) = 100 / (1,225 × 9,81) ≈ 8,3 m je hPa\n\n"
    "**Deshalb** verschiebt jedes falsch gestellte Hektopascal die "
    "Anzeige um gut acht Meter. Ein um 18 hPa zu hoch eingestellter "
    "Hoehenmesser (1013 statt 995) zeigt rund 150 m zu viel an.\n\n"
    "Weiter oben wird die Zahl groesser, weil ρ abnimmt: in 5000 m sind "
    "es schon rund 15 m je hPa. Fuer die Platzrunde reicht die 8.\n\n"
    "**„From high to low, look out below“** ist genau das: "
    "Fliegt man in tieferen Druck, ohne nachzustellen, misst die Dose "
    "weniger Druck und haelt das faelschlich fuer Hoehe. Man ist tiefer "
    "als angezeigt — um acht Meter je Hektopascal.",

    "## Symbols\n\n"
    "`p` air pressure, Pa (1 hPa = 100 Pa). `ρ` air density, kg/m³; "
    "1.225 at sea level. `g` gravitational acceleration, 9.81 m/s². "
    "`h` height, m. `dp`, `dh` small changes in pressure and height.\n\n"
    "## Derivation: the hydrostatic equation\n\n"
    "Air pressure at a point is the weight of the column of air above it, "
    "spread over the area. Climb by `dh` and exactly the layer `dh` drops "
    "out of that column.\n\n"
    "Over the area `A` that layer has volume `A·dh`, hence mass "
    "`ρ·A·dh` and weight `ρ·A·dh·g`. Its contribution to the pressure is "
    "weight over area — `A` cancels:\n\n"
    "    dp = − ρ · g · dh\n\n"
    "The minus because pressure falls with height. This is the "
    "hydrostatic equation, and it holds in any fluid at rest.\n\n"
    "## And why one hectopascal is about eight metres\n\n"
    "Solved for `dh` and evaluated at sea level:\n\n"
    "    dh = dp / (ρ·g) = 100 / (1.225 × 9.81) ≈ 8.3 m per hPa\n\n"
    "**That is why** every hectopascal set wrongly shifts the reading by "
    "a good eight metres. An altimeter set 18 hPa too high (1013 instead "
    "of 995) over-reads by about 150 m.\n\n"
    "Higher up the figure grows, because ρ falls: at 5000 m it is already "
    "about 15 m per hPa. For the circuit, 8 will do.\n\n"
    "**“From high to low, look out below”** is exactly this: fly "
    "into lower pressure without resetting and the capsule measures less "
    "pressure and mistakes that for height. You are lower than indicated "
    "— by eight metres per hectopascal."),

"n-kurse": t(
    "## Formelzeichen\n\n"
    "`α` Vorhaltewinkel, Grad. `v_q` Querwindanteil, km/h. `v` "
    "Eigengeschwindigkeit, km/h. `rw` rechtweisender Kurs (gegen "
    "geografisch Nord), Grad. `mw` missweisender Kurs (gegen magnetisch "
    "Nord), Grad. **rad** — das Bogenmass: der Winkel, gemessen als "
    "Bogenlaenge auf dem Einheitskreis.\n\n"
    "## Vorab: warum 1 rad = 57,3° ist\n\n"
    "Der volle Kreis hat den Umfang 2π und zugleich 360°. Ein Bogenmass "
    "ist also\n\n"
    "    1 rad = 360° / (2π) = 180°/π = 57,296°\n\n"
    "## Und warum sin α ≈ α gilt\n\n"
    "Aus der Taylorreihe des Sinus:\n\n"
    "    sin α = α − α³/6 + α⁵/120 − ...      (α in rad)\n\n"
    "Fuer kleine α ist `α³/6` winzig gegen α. Bei 10° (0,175 rad) betraegt "
    "der Fehler 0,5 %, bei 20° (0,35 rad) 2 %, bei 30° 4,5 %. **Nur im "
    "Bogenmass** — in Grad gilt die Reihe nicht.\n\n"
    "## Herleitung: woher die 60 im Vorhaltewinkel kommt\n\n"
    "Der Wind schiebt quer. Aus Eigengeschwindigkeit und Querwind wird "
    "ein rechtwinkliges Dreieck, und exakt gilt\n\n"
    "    sin α = v_q / v\n\n"
    "Damit koennte man im Cockpit wenig anfangen. Mit `sin α ≈ α` in "
    "rad und `1 rad = 57,3°`:\n\n"
    "    α [°] ≈ (v_q / v) × 57,3\n\n"
    "Aufgerundet auf **60**, weil sich damit im Kopf rechnen laesst und "
    "der Fehler zur sicheren Seite geht: Man haelt etwas mehr vor als "
    "noetig. Daher der Name **1-in-60-Regel** — 1 Einheit Versatz auf 60 "
    "Einheiten Strecke ist ein Grad.\n\n"
    "**Wie weit sie traegt:** bis etwa 20 Grad gut, darueber rechnet man "
    "besser richtig.\n\n"
    "## Und die Missweisung\n\n"
    "Sie ist kein Rechentrick, sondern eine Ortsangabe: der Winkel "
    "zwischen geografischem und magnetischem Nordpol an dieser Stelle der "
    "Erde. Die Karte ist rechtweisend, der Kompass missweisend. Zeigt der "
    "magnetische Pol vom Standort aus **westlich** des geografischen, "
    "dann zeigt der Kompass fuer dieselbe Richtung eine groessere Zahl:\n\n"
    "    mw = rw + Missweisung        (West positiv, Ost negativ)\n\n"
    "Merksatz: *Missweisung West, Kompass zeigt mehr.*",

    "## Symbols\n\n"
    "`α` drift angle, degrees. `v_c` crosswind component, km/h. `v` "
    "airspeed, km/h. `T` true track (against geographic north), degrees. "
    "`M` magnetic track, degrees. **rad** — radian measure: the angle "
    "measured as arc length on the unit circle.\n\n"
    "## First: why 1 rad = 57.3°\n\n"
    "The full circle has circumference 2π and at the same time 360°. So "
    "one radian is\n\n"
    "    1 rad = 360° / (2π) = 180°/π = 57.296°\n\n"
    "## And why sin α ≈ α holds\n\n"
    "From the Taylor series of the sine:\n\n"
    "    sin α = α − α³/6 + α⁵/120 − ...      (α in rad)\n\n"
    "For small α, `α³/6` is tiny against α. At 10° (0.175 rad) the error "
    "is 0.5 %, at 20° (0.35 rad) 2 %, at 30° 4.5 %. **Only in radians** — "
    "in degrees the series does not hold.\n\n"
    "## Derivation: where the 60 in the drift angle comes from\n\n"
    "The wind pushes you sideways. Airspeed and crosswind make a "
    "right-angled triangle, and exactly\n\n"
    "    sin α = v_c / v\n\n"
    "which is of little use in a cockpit. With `sin α ≈ α` in radians and "
    "`1 rad = 57.3°`:\n\n"
    "    α [°] ≈ (v_c / v) × 57.3\n\n"
    "rounded up to **60**, because that can be done in the head and the "
    "error falls on the safe side: you crab slightly more than needed. "
    "Hence the name **1-in-60 rule** — one unit of offset in sixty units "
    "of distance is one degree.\n\n"
    "**How far it carries:** good to about 20 degrees; beyond that, do it "
    "properly.\n\n"
    "## And variation\n\n"
    "It is not an arithmetic trick but a statement about place: the angle "
    "between the geographic and the magnetic north pole at this spot on "
    "the earth. The chart is true, the compass is magnetic. If the "
    "magnetic pole lies **west** of the geographic one as seen from here, "
    "the compass shows a larger number for the same direction:\n\n"
    "    magnetic = true + variation        (west positive, east negative)\n\n"
    "Mnemonic: *variation west, magnetic best.*"),

}
